# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lothieve <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/04 15:02:47 by lothieve          #+#    #+#              #
#    Updated: 2022/11/28 13:49:14 by lothieve         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - db:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    restart: always
    networks:
      - transcendance
  nest:
    container_name: nest
    build: nest
    depends_on:
      - db
    restart: always
    networks:
      - transcendance
    ports:
      - 3000:3000
    # vue:
    # build: front
    # ports:
    #  - "8080:8080"
    # container_name: vue
    # depends_on:
    #   - nest
    # networks:
    #   - transcendance
    # volumes:
    #   - type: bind
    #     source: front
    #     target: /usr/src/app/front/src
    # restart: always
    # command: npm run serve
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - transcendance
networks:
  transcendance:
volumes:
  db:
  pgadmin:
